export type Element = "fire" | "water" | "air" | "earth" | "quantum";

export interface ScheduleEvent {
  time: string;
  event: string;
  detail?: string;
  element: Element;
  secondElement?: Element;
  thirdElement?: Element;
  location?: string;
  gloss?: string;
  limited?: boolean;
  fee?: string;
  hosts?: string[];
}

export interface ScheduleDay {
  label: string;
  headingText: string;
  headingIcon: "moon" | "flame" | "leaf";
  theme: string;
  events: ScheduleEvent[];
}

export const LIONSGATE_GLOSS =
  "Our gathering falls on August 8th — the Lion's Gate Portal. A day of heightened energy and intentional outdoor ceremony. We step outside together at 8:08 AM to meet the day with full presence — mountain air, open sky, and the earth beneath bare feet.";
export const CONTRAST_GLOSS =
  "Alternating cold water immersion and heat activates circulation, reduces inflammation, and powerfully grounds the nervous system. Sessions run all day Friday–Sunday in 30-minute slots — sauna holds 4 people maximum. Must be booked in advance. Facilitated by Ashleigh Bicknell.";
export const LABYRINTH_GLOSS =
  "One path in. One path out. The labyrinth garden is open throughout the weekend for silent walking, integration, and personal reflection between ceremonies.";

export const scheduleDays: ScheduleDay[] = [
  {
    label: "Friday · Aug 7",
    headingText: "Arrival + Grounding",
    headingIcon: "moon",
    theme: "Land · Arrival · Intention · Past",
    events: [
      {
        time: "1:00 PM",
        event: "Opening Ceremony · Dance Alchemy",
        detail: "Ashleigh guides somatic movement that leads us through the elements. A perfect opening ceremony for our weekend.",
        element: "fire", location: "Main Stage",
        hosts: ["ashleigh"],
      },
      {
        time: "2:00 PM",
        event: "Quantum Light Activation",
        detail: "Activate your healing with phototherapy — quantum light technology to spark cellular renewal and elevate your energy field as you arrive.",
        element: "quantum", location: "Main Stage",
        hosts: ["shawn"],
      },
      {
        time: "2:00 PM",
        event: "Paddleboard Yoga",
        detail: "All levels, beginner-friendly flow on the lake — you might get wet!",
        element: "water", location: "Lakeside",
        limited: true,
        hosts: ["alice"],
      },
      {
        time: "3:00 PM",
        event: "Draggon Stargates",
        detail: "A workshop on the Draggon lineage and how to connect to our Draggon essence.",
        element: "fire", location: "Bonfire",
        hosts: ["akatale"],
      },
      {
        time: "3:00 PM",
        event: "Guided Meditation",
        detail: "Guided bilateral movement for a deeply relaxing, grounding session.",
        element: "earth", location: "Main Stage",
        hosts: ["dixie"],
      },
      {
        time: "3:00 PM",
        event: "Intro Aerial",
        detail: "Beginner silks flow — learn the basics of floating and flying. 6 people max.",
        element: "air", location: "Aerial Rig",
        limited: true,
        hosts: ["beth"],
      },
      {
        time: "3:00 PM",
        event: "Contrast Therapy",
        detail: "30 min · Cold plunge + heat cycling to activate circulation, reduce inflammation, and ground your nervous system.",
        element: "water", secondElement: "fire",
        location: "Lakeside",
        gloss: CONTRAST_GLOSS,
        limited: true,
        hosts: ["ashleigh"],
      },
      {
        time: "4:00 PM",
        event: "Tarot + Tea Party",
        detail: "Divinators gather in the garden to share readings, sip community tea, and activate the space. Come as you are — daily at 4 PM.",
        element: "earth", location: "Labyrinth Garden",
      },
      {
        time: "4:00 PM",
        event: "Yin Yoga & Sound Savasana",
        detail: "Restorative long-hold poses melting into a sound savasana.",
        element: "earth", secondElement: "quantum",
        location: "Main Stage",
        hosts: ["mary"],
      },
      {
        time: "5:00 PM",
        event: "Keys of Kreation",
        detail: "Unlock your infinite potential of creative expression in this 2-hour immersive workshop.",
        element: "fire", location: "Main Stage",
        hosts: ["j-brave"],
      },
      {
        time: "7:30 PM",
        event: "Sacred Heart Activation",
        detail: "Cacao ceremony and heart activation — an opening of the sacred heart through ceremony, sound, and intention around the fire.",
        element: "fire", location: "Bonfire",
        hosts: ["az", "avalon-starling"],
      },
      {
        time: "8:00 PM",
        event: "Ecstatic Dance",
        element: "fire", secondElement: "air", thirdElement: "quantum",
        location: "Main Stage",
        hosts: ["flowscape"],
      },
    ],
  },
  {
    label: "Saturday · Aug 8",
    headingText: "Activation + Transformation",
    headingIcon: "flame",
    theme: "Lion's Gate · Expansion · Ceremony · Present",
    events: [
      {
        time: "7:00 AM",
        event: "Floating Sound Bath",
        detail: "Handpan music and ambient sound washing over the still morning lake.",
        element: "water", secondElement: "air", thirdElement: "quantum",
        location: "Lakeside",
        hosts: ["peace-pixy"],
      },
      {
        time: "8:00 AM",
        event: "Lionsgate Activation 🦁 + Floating Sound Bath",
        detail: "Float in an aerial silk hammock or on a paddleboard as the Lion's Gate opens — ceremony at 8:08 AM.",
        element: "water", secondElement: "air", thirdElement: "quantum",
        location: "Lakeside · Aerial",
        gloss: LIONSGATE_GLOSS,
        hosts: ["avalon-starling"],
      },
      {
        time: "8:30 AM",
        event: "Pranayama Breathwork",
        detail: "30 min · A guided breathing session from the Isha Foundation to ground and energize before yoga.",
        element: "air", secondElement: "earth",
        location: "Main Stage",
        hosts: ["logan-forehand"],
      },
      {
        time: "9:00 AM",
        event: "Yoga for Health",
        detail: "90 min · An energizing embodiment practice weaving sound, breath, and asana to build genuine health from the inside out.",
        element: "earth", location: "Main Stage",
        hosts: ["logan-forehand"],
      },
      {
        time: "9:30 AM",
        event: "Contrast Therapy",
        detail: "30 min · Cold plunge + heat cycling — ground and reset before the day unfolds.",
        element: "water", secondElement: "fire",
        location: "Lakeside",
        gloss: CONTRAST_GLOSS,
        limited: true,
        hosts: ["ashleigh"],
      },
      {
        time: "10:30 AM",
        event: "Quantum Light Activation",
        detail: "Activate your healing with phototherapy — harness quantum light to renew the body and brighten the field.",
        element: "quantum", location: "Main Stage",
        hosts: ["shawn"],
      },
      {
        time: "10:00 AM",
        event: "Intro Aerial",
        detail: "Floating in silks — a supported introduction to aerial flight. 6 people max.",
        element: "air", location: "Aerial Rig",
        limited: true,
        hosts: ["beth"],
      },
      {
        time: "11:00 AM",
        event: "Feel Good Flow",
        detail: "An uplifting all-levels flow to embody the breath, open the body, and raise your vibration.",
        element: "earth", secondElement: "air",
        location: "Main Stage",
        hosts: ["jenni"],
      },
      {
        time: "12:00 PM",
        event: "The Expression of the Soul",
        detail: "An education workshop exploring the soul as multidimensional. We will connect with the higher self, the one soul, and expand and deepen our soul expression.",
        element: "fire", location: "Main Stage",
        hosts: ["akatale", "avalon-starling"],
      },
      {
        time: "1:00 PM",
        event: "Paddleboard Yoga",
        detail: "An afternoon flow on the water — all levels welcome.",
        element: "water", location: "Lakeside",
        limited: true,
        hosts: ["ashleigh"],
      },
      {
        time: "2:00 PM",
        event: "A Trauma-Informed Approach to Self-Defense",
        detail: "Advanced practical self-defense skills combined with nervous system regulation, boundary setting, and how to respond from confidence rather than fear.",
        element: "earth", location: "Main Stage",
        hosts: ["meghan"],
      },
      {
        time: "2:00 PM",
        event: "Intro Aerial",
        detail: "Beginner silks session — float, stretch, and play. 6 people max.",
        element: "air", location: "Aerial Rig",
        limited: true,
        hosts: ["beth"],
      },
      {
        time: "3:00 PM",
        event: "Flow & Touch — A Partner Yogassage Experience",
        detail: "Experience the healing combination of mindful movement, supportive touch, and breath. Learn simple partner techniques to release tension, improve mobility, and cultivate meaningful connection.",
        element: "earth", location: "Main Stage",
        hosts: ["sarah"],
      },
      {
        time: "3:00 PM",
        event: "Authentic Relating Practice",
        detail: "Connection games and guided practices that drop us below small talk into real presence with one another.",
        element: "fire", location: "Labyrinth Garden",
        hosts: ["az"],
      },
      {
        time: "4:00 PM",
        event: "Roots for Recovery",
        detail: "Yin yoga with long holds and MFR props, ending in a Tibetan bowl and gong sound bath.",
        element: "earth", secondElement: "quantum",
        location: "Main Stage",
        hosts: ["jon"],
      },
      {
        time: "4:00 PM",
        event: "Tarot + Tea Party",
        detail: "Daily gathering of readers and seekers in the garden — tea, cards, and connection.",
        element: "earth", location: "Labyrinth Garden",
      },
      {
        time: "5:00 PM",
        event: "Guzheng · Five Elements Sound Healing",
        detail: "A live guzheng performance drawing from the ancient Chinese tradition of five musical tones — Gong, Shang, Jue, Zhi, and Yu — each resonating with the Five Elements and organ systems of the body. Designed to promote relaxation, mindfulness, and balance through music.",
        element: "quantum", secondElement: "earth",
        location: "Main Stage",
        hosts: ["jing-xi-kang"],
      },
      {
        time: "5:30 PM",
        event: "Contrast Therapy",
        detail: "30 min · Final session of the day — prepare your body for an evening of ceremony.",
        element: "water", secondElement: "fire",
        location: "Lakeside",
        gloss: CONTRAST_GLOSS,
        limited: true,
        hosts: ["ashleigh"],
      },
      {
        time: "6:00 PM",
        event: "S7INGRAE & Brackish",
        detail: "A live set to carry the community from afternoon practice into the evening's ceremony.",
        element: "air", secondElement: "quantum",
        location: "Main Stage · Live Music",
        hosts: ["s7ngrae"],
      },
      {
        time: "7:00 PM",
        event: "Cacao Ceremony",
        detail: "Gather at the fire to share ceremonial cacao and open the heart before the night's dance.",
        element: "fire", location: "Bonfire",
      },
      {
        time: "8:00 PM",
        event: "Ecstatic Dance",
        element: "fire", secondElement: "air", thirdElement: "quantum",
        location: "Main Stage",
        hosts: ["j-brave"],
      },
      {
        time: "10:00 PM",
        event: "Ecstatic Dance",
        element: "fire", secondElement: "air", thirdElement: "quantum",
        location: "Main Stage",
        hosts: ["flowscape"],
      },
    ],
  },
  {
    label: "Sunday · Aug 9",
    headingText: "Integration + Community",
    headingIcon: "leaf",
    theme: "Soft Landing · Heart Opening · Family Day · Future",
    events: [
      {
        time: "8:00 AM",
        event: "Sound Journey",
        detail: "Handpan music and ambient sound bath nestled in the labyrinth garden.",
        element: "earth", secondElement: "air", thirdElement: "quantum",
        location: "Labyrinth Garden",
        gloss: LABYRINTH_GLOSS,
        hosts: ["peace-pixy"],
      },
      {
        time: "9:00 AM",
        event: "Contrast Therapy",
        detail: "30 min · Cold plunge + sauna cycling, available all day. Must be booked in advance.",
        element: "water", secondElement: "fire",
        location: "Lakeside",
        gloss: CONTRAST_GLOSS,
        limited: true,
        hosts: ["ashleigh"],
      },
      {
        time: "9:00 AM",
        event: "Pranayama Breathwork",
        detail: "30 min · A guided breathing session from the Isha Foundation to ground and open before the day's ceremonies.",
        element: "air", secondElement: "earth",
        location: "Main Stage",
        hosts: ["logan-forehand"],
      },
      {
        time: "9:30 AM",
        event: "Miracle of Mind",
        detail: "30 min · Beginner-friendly guided meditation and open discussion on the power of the mind.",
        element: "earth", location: "Labyrinth Garden",
        hosts: ["logan-forehand"],
      },
      {
        time: "10:00 AM",
        event: "Activate Your Light Floating Sound Bath",
        detail: "A combined light activation and floating sound bath — Shawn and Avalon guide you into quantum light and sound to integrate the weekend's medicine.",
        element: "water", secondElement: "air", thirdElement: "quantum",
        location: "Lakeside",
        hosts: ["shawn", "avalon-starling"],
      },
      {
        time: "11:11 AM",
        event: "Message from the Bees · Ecstatic Dance",
        detail: "Let the bees speak through your body — an ecstatic dance to activate the Labyrinth Garden portal and move the medicine.",
        element: "earth", secondElement: "fire", thirdElement: "quantum",
        location: "Labyrinth Garden",
        hosts: ["mary"],
      },
      {
        time: "11:30 AM",
        event: "Contrast Therapy",
        detail: "30 min · Invigorate and integrate — book in advance.",
        element: "water", secondElement: "fire",
        location: "Lakeside",
        gloss: CONTRAST_GLOSS,
        limited: true,
        hosts: ["ashleigh"],
      },
      {
        time: "12:00 PM",
        event: "Shawn Zuke",
        detail: "Soulful live music to open the family-day afternoon.",
        element: "air", secondElement: "quantum",
        location: "Main Stage · Live Music",
        hosts: ["shawn-zuke"],
      },
      {
        time: "1:00 PM",
        event: "Kuf Knotz + Christine Elise",
        detail: "Conscious hip-hop meets raw folk — an uplifting 2-hour live collaboration.",
        element: "air", secondElement: "quantum",
        location: "Main Stage · Live Music",
        hosts: ["kuf-knotz", "christine-elise"],
      },
      {
        time: "1:00 PM",
        event: "Kids Paddleboard",
        detail: "A playful, safe introduction to paddleboarding for young adventurers — family day on the lake!",
        element: "water", location: "Lakeside",
        limited: true,
        hosts: ["alice"],
      },
      {
        time: "2:00 PM",
        event: "Intro Aerial for Kids",
        detail: "A playful introduction to silks for little flyers. 6 kids max.",
        element: "air", location: "Aerial Rig",
        limited: true,
        hosts: ["beth"],
      },
      {
        time: "3:00 PM",
        event: "Paddleboard Yoga",
        detail: "A final all-levels flow on the water — integrate the weekend floating under the open sky.",
        element: "water", location: "Lakeside",
        limited: true,
        hosts: ["alice"],
      },
      {
        time: "3:15 PM",
        event: "J Brave",
        detail: "45 minutes of conscious lyricism and heart-forward music.",
        element: "air", secondElement: "quantum",
        location: "Main Stage · Live Music",
        hosts: ["j-brave"],
      },
      {
        time: "4:00 PM",
        event: "ÂKÅTÂLĖ",
        detail: "A live sonic journey to gather the community toward closing.",
        element: "air", secondElement: "quantum",
        location: "Main Stage · Live Music",
        hosts: ["akatale"],
      },
      {
        time: "3:00 PM",
        event: "Pendulum Readings & Salt Intention Workshop",
        detail: "An immersive workshop on pendulum divination and the art of creating salt intentions — a sacred pre-ceremony practice before the Tarot + Tea.",
        element: "earth", location: "Labyrinth Garden",
        hosts: ["mystical-moon-dance"],
      },
      {
        time: "4:00 PM",
        event: "Tarot + Tea Party",
        detail: "The final daily garden gathering — close the weekend with mystery and magic.",
        element: "earth", location: "Labyrinth Garden",
        hosts: ["mystical-moon-dance"],
      },
      {
        time: "5:00 PM",
        event: "Closing Ceremony",
        detail: "Led by Avalon Starling — we will make a love bridge to send you home with a full heart.",
        element: "fire", location: "Main Stage",
        hosts: ["avalon-starling"],
      },
      {
        time: "6:00 PM",
        event: "Band Jam",
        detail: "The weekend's musicians take the stage together for a live collaborative jam — one last wave of sound as a community.",
        element: "air", secondElement: "quantum",
        location: "Main Stage",
      },
      {
        time: "7:00 PM",
        event: "Ecstatic Dance",
        detail: "7–9 PM · Close the weekend dancing.",
        element: "fire", secondElement: "air", thirdElement: "quantum",
        location: "Main Stage",
        hosts: ["flowscape"],
      },
    ],
  },
];
