export type Element = "fire" | "water" | "air" | "earth" | "sound";

export interface ScheduleEvent {
  time: string;
  event: string;
  detail?: string;
  element: Element;
  secondElement?: Element;
  thirdElement?: Element;
  location?: string;
  gloss?: string;
  limited?: boolean;
  fee?: string;
  link?: string;
  hosts?: string[];
}

export interface ScheduleDay {
  label: string;
  headingText: string;
  headingIcon: "moon" | "flame" | "leaf";
  theme: string;
  events: ScheduleEvent[];
}

export const LIONSGATE_GLOSS =
  "Our gathering falls on August 8th — the Lion's Gate Portal. A day of heightened energy and intentional outdoor ceremony. We step outside together at 8:08 AM to meet the day with full presence — mountain air, open sky, and the earth beneath bare feet.";
export const LABYRINTH_GLOSS =
  "One path in. One path out. The labyrinth garden is open throughout the weekend for silent walking, integration, and personal reflection between ceremonies.";

export const scheduleDays: ScheduleDay[] = [
  {
    label: "Friday · Aug 7",
    headingText: "Arrival + Grounding",
    headingIcon: "moon",
    theme: "Land · Arrival · Intention · Past",
    events: [
      {
        time: "10:00 AM",
        event: "Gates Open · Check-in",
        detail: "Welcome to Wellness Weekend — arrive, settle in, and find your space. Check in at the welcome tent.",
        element: "earth", location: "Welcome Tent",
      },
      {
        time: "12:00 PM",
        event: "Opening Ceremony",
        detail: "A grounding arrival ceremony to open the weekend — setting intention, calling in community, and landing in the body before the journey begins.",
        element: "fire", location: "Main Stage",
        hosts: [],
      },
      {
        time: "1:00 PM",
        event: "Yoga for Health",
        detail: "75 min · A comprehensive Isha Foundation practice — Yoga Namaskar, Nadi Shuddhi breathing (a technique that cleanses the energy pathways and restores balance), and Miracle of Mind meditation — woven into a single flowing session.",
        element: "earth", secondElement: "air",
        location: "Main Stage",
        hosts: ["logan-forehand"],
      },
      {
        time: "1:00 PM",
        event: "Lakeside Sauna Opens",
        detail: "The Lakeside Sauna by Solstice Saunas opens for the weekend — pay at the gate · $22/1 hr · $45/all day · $99/full weekend. No booking needed.",
        element: "fire",
        location: "Lakeside",
        link: "/contrast-therapy",
      },
      {
        time: "2:00 PM",
        event: "Quantum Light Activation",
        detail: "Activate your healing with phototherapy — quantum light technology to spark cellular renewal and elevate your energy field as you arrive.",
        element: "fire", location: "Main Stage",
        hosts: ["shawn"],
      },
      {
        time: "2:00 PM",
        event: "Paddleboard Yoga",
        detail: "All levels, beginner-friendly flow on the lake — you might get wet!",
        element: "water", location: "Lakeside",
        limited: true,
        link: "/paddleboard",
        hosts: ["alice"],
      },
      {
        time: "3:00 PM",
        event: "Draggon Stargates",
        detail: "A workshop on the Draggon lineage and how to connect to our Draggon essence.",
        element: "fire", location: "Bonfire",
        hosts: ["akatale"],
      },
      {
        time: "3:00 PM",
        event: "Guided Meditation",
        detail: "Guided bilateral movement for a deeply relaxing, grounding session.",
        element: "earth", location: "Main Stage",
        hosts: ["dixie"],
      },
      {
        time: "3:00 PM",
        event: "Intro Aerial",
        detail: "Beginner silks flow — learn the basics of floating and flying. 6 people max.",
        element: "air", location: "Aerial Rig",
        limited: true,
        link: "/aerial",
        hosts: ["beth"],
      },
      {
        time: "4:00 PM",
        event: "Tarot + Tea Party",
        detail: "Divinators gather in the lodge's upstairs lounge to share readings, sip community tea, and activate the space. Come as you are — daily at 4 PM.",
        element: "air", location: "Lodge · Upstairs Lounge",
      },
      {
        time: "4:00 PM",
        event: "Yin Yoga & Sound Savasana",
        detail: "Restorative long-hold poses melting into a sound savasana.",
        element: "earth", secondElement: "sound",
        location: "Main Stage",
        hosts: ["mary"],
      },
      {
        time: "5:00 PM",
        event: "Keys of Kreation",
        detail: "Unlock your infinite potential of creative expression in this 2-hour immersive workshop.",
        element: "fire", location: "Main Stage",
        hosts: ["j-brave"],
      },
      {
        time: "6:00 PM",
        event: "Intro Aerial · Sunset Session",
        detail: "Beginner silks flow as the light softens — float, stretch, and play. 6 people max.",
        element: "air", location: "Aerial Rig",
        limited: true,
        link: "/aerial",
        hosts: ["beth"],
      },
      {
        time: "7:30 PM",
        event: "Sacred Heart Activation",
        detail: "Cacao ceremony and heart activation — an opening of the sacred heart through ceremony, sound, and intention around the fire.",
        element: "fire", location: "Bonfire",
        hosts: ["az", "avalon-starling"],
      },
      {
        time: "8:00 PM",
        event: "Ecstatic Dance",
        element: "fire", secondElement: "air",
        location: "Main Stage",
        fee: "Silk hammock rental available · $20/30 min · See /aerial",
        hosts: ["flowscape"],
      },
    ],
  },
  {
    label: "Saturday · Aug 8",
    headingText: "Activation + Transformation",
    headingIcon: "flame",
    theme: "Lion's Gate · Expansion · Ceremony · Present",
    events: [
      {
        time: "7:00 AM",
        event: "Floating Sound Bath",
        detail: "Handpan music and ambient sound washing over the still morning lake.",
        element: "water", secondElement: "air", thirdElement: "sound",
        location: "Lakeside",
        hosts: ["peace-pixy"],
      },
      {
        time: "8:00 AM",
        event: "Lionsgate Activation 🦁 + Floating Sound Bath",
        detail: "Float in an aerial silk hammock or on a paddleboard as the Lion's Gate opens — ceremony at 8:08 AM.",
        element: "water", secondElement: "air", thirdElement: "sound",
        location: "Lakeside · Aerial",
        gloss: LIONSGATE_GLOSS,
        hosts: ["avalon-starling"],
      },
      {
        time: "9:00 AM",
        event: "Lakeside Sauna",
        detail: "The Solstice Saunas lakeside sauna is open all day — pay at the gate · $22/1 hr · $45/all day · $99/full weekend. No booking needed.",
        element: "fire", secondElement: "water",
        location: "Lakeside",
        link: "/contrast-therapy",
      },
      {
        time: "9:45 AM",
        event: "Isha Kriya",
        detail: "45 min · A meditation process from Sadhguru to help you get in touch with the source of existence.",
        element: "air", secondElement: "earth",
        location: "Main Stage",
        hosts: ["logan-forehand"],
      },
      {
        time: "10:00 AM",
        event: "Intro Aerial",
        detail: "Floating in silks — a supported introduction to aerial flight. 6 people max.",
        element: "air", location: "Aerial Rig",
        limited: true,
        link: "/aerial",
        hosts: ["beth"],
      },
      {
        time: "10:30 AM",
        event: "Quantum Light Activation",
        detail: "Activate your healing with phototherapy — harness quantum light to renew the body and brighten the field.",
        element: "fire", location: "Main Stage",
        hosts: ["shawn"],
      },
      {
        time: "11:00 AM",
        event: "Feel Good Flow",
        detail: "An uplifting all-levels flow to embody the breath, open the body, and raise your vibration.",
        element: "earth", secondElement: "air",
        location: "Main Stage",
        hosts: ["jenni"],
      },
      {
        time: "12:00 PM",
        event: "The Expression of the Soul",
        detail: "An education workshop exploring the soul as multidimensional. We will connect with the higher self, the one soul, and expand and deepen our soul expression.",
        element: "fire", location: "Main Stage",
        hosts: ["akatale", "avalon-starling"],
      },
      {
        time: "1:00 PM",
        event: "Paddleboard Yoga",
        detail: "An afternoon flow on the water — all levels welcome.",
        element: "water", location: "Lakeside",
        limited: true,
        link: "/paddleboard",
        hosts: ["alice"],
      },
      {
        time: "2:00 PM",
        event: "A Trauma-Informed Approach to Self-Defense",
        detail: "Advanced practical self-defense skills combined with nervous system regulation, boundary setting, and how to respond from confidence rather than fear.",
        element: "earth", location: "Main Stage",
        hosts: ["meghan"],
      },
      {
        time: "2:00 PM",
        event: "Intro Aerial",
        detail: "Beginner silks session — float, stretch, and play. 6 people max.",
        element: "air", location: "Aerial Rig",
        limited: true,
        link: "/aerial",
        hosts: ["beth"],
      },
      {
        time: "3:00 PM",
        event: "Flow & Touch — A Partner Yogassage Experience",
        detail: "Experience the healing combination of mindful movement, supportive touch, and breath. Learn simple partner techniques to release tension, improve mobility, and cultivate meaningful connection.",
        element: "earth", location: "Main Stage",
        hosts: ["sarah"],
      },
      {
        time: "3:00 PM",
        event: "Authentic Relating Practice",
        detail: "Connection games and guided practices that drop us below small talk into real presence with one another.",
        element: "fire", location: "Labyrinth Garden",
        hosts: ["az"],
      },
      {
        time: "4:00 PM",
        event: "Roots for Recovery",
        detail: "Yin yoga with long holds and MFR props, ending in a Tibetan bowl and gong sound bath.",
        element: "earth", secondElement: "sound",
        location: "Main Stage",
        hosts: ["jon"],
      },
      {
        time: "4:00 PM",
        event: "Tarot + Tea Party",
        detail: "Daily gathering of readers and seekers in the lodge's upstairs lounge — tea, cards, and connection.",
        element: "air", location: "Lodge · Upstairs Lounge",
      },
      {
        time: "5:00 PM",
        event: "Guzheng · Five Elements Sound Healing",
        detail: "A live guzheng performance drawing from the ancient Chinese tradition of five musical tones — Gong, Shang, Jue, Zhi, and Yu — each resonating with the Five Elements and organ systems of the body. Designed to promote relaxation, mindfulness, and balance through music.",
        element: "sound", secondElement: "earth",
        location: "Main Stage",
        hosts: ["jing-xi-kang"],
      },
      {
        time: "6:00 PM",
        event: "S7INGRAE & Brackish",
        detail: "A live set to carry the community from afternoon practice into the evening's ceremony.",
        element: "air",
        location: "Main Stage · Live Music",
        hosts: ["s7ngrae"],
      },
      {
        time: "7:00 PM",
        event: "Cacao Ceremony",
        detail: "Gather at the fire to share ceremonial cacao and open the heart before the night's dance.",
        element: "fire", location: "Bonfire",
      },
      {
        time: "8:00 PM",
        event: "Ecstatic Dance",
        element: "fire", secondElement: "air",
        location: "Main Stage",
        fee: "Silk hammock rental available · $20/30 min · See /aerial",
        hosts: ["j-brave"],
      },
      {
        time: "10:00 PM",
        event: "Ecstatic Dance",
        element: "fire", secondElement: "air",
        location: "Main Stage",
        fee: "Silk hammock rental available · $20/30 min · See /aerial",
        hosts: ["flowscape"],
      },
    ],
  },
  {
    label: "Sunday · Aug 9",
    headingText: "Integration + Community",
    headingIcon: "leaf",
    theme: "Soft Landing · Heart Opening · Family Day · Future",
    events: [
      {
        time: "8:00 AM",
        event: "Sound Journey",
        detail: "Handpan music and ambient sound bath nestled in the labyrinth garden.",
        element: "sound", secondElement: "earth",
        location: "Labyrinth Garden",
        gloss: LABYRINTH_GLOSS,
        hosts: ["peace-pixy"],
      },
      {
        time: "9:00 AM",
        event: "Lakeside Sauna",
        detail: "The Solstice Saunas lakeside sauna is open all day — pay at the gate · $22/1 hr · $45/all day · $99/full weekend. No booking needed.",
        element: "fire", secondElement: "water",
        location: "Lakeside",
        link: "/contrast-therapy",
      },
      {
        time: "9:30 AM",
        event: "Isha Kriya",
        detail: "30 min · A meditation process from Sadhguru to help you get in touch with the source of existence.",
        element: "air", secondElement: "earth",
        location: "Main Stage",
        hosts: ["logan-forehand"],
      },
      {
        time: "10:00 AM",
        event: "Upa Yoga",
        detail: "30 min · A gentle Isha Foundation practice for all ages 7+ — Yoga Namaskar, arm and neck sequences, and Nadi Shuddhi breathing to ground and integrate the afternoon.",
        element: "earth", secondElement: "air",
        location: "Main Stage",
        hosts: ["logan-forehand"],
      },
      {
        time: "10:00 AM",
        event: "Activate Your Light Floating Sound Bath",
        detail: "A combined light activation and floating sound bath — Shawn and Avalon guide you into quantum light and sound to integrate the weekend's medicine.",
        element: "water", secondElement: "air", thirdElement: "sound",
        location: "Lakeside",
        hosts: ["shawn", "avalon-starling"],
      },
      {
        time: "10:30 AM",
        event: "Intro Aerial",
        detail: "Beginner silks flow — learn the basics of floating and flying. 6 people max.",
        element: "air", location: "Aerial Rig",
        limited: true,
        link: "/aerial",
        hosts: ["beth"],
      },
      {
        time: "11:11 AM",
        event: "Message from the Bees · Ecstatic Dance",
        detail: "Let the bees speak through your body — an ecstatic dance to activate the Labyrinth Garden portal and move the medicine.",
        element: "earth", secondElement: "fire",
        location: "Labyrinth Garden",
        fee: "Silk hammock rental available · $20/30 min · See /aerial",
        hosts: ["mary"],
      },
      {
        time: "12:00 PM",
        event: "Shawn Zuke",
        detail: "Soulful live music to open the family-day afternoon.",
        element: "air",
        location: "Main Stage · Live Music",
        hosts: ["shawn-zuke"],
      },
      {
        time: "1:00 PM",
        event: "Kuf Knotz + Christine Elise",
        detail: "Conscious hip-hop meets raw folk — an uplifting 2-hour live collaboration.",
        element: "air",
        location: "Main Stage · Live Music",
        hosts: ["kuf-knotz", "christine-elise"],
      },
      {
        time: "1:00 PM",
        event: "Kids Paddleboard",
        detail: "A playful, safe introduction to paddleboarding for young adventurers — family day on the lake!",
        element: "water", location: "Lakeside",
        limited: true,
        link: "/paddleboard",
        hosts: ["alice"],
      },
      {
        time: "2:00 PM",
        event: "Intro Aerial for Kids",
        detail: "A playful introduction to silks for little flyers. 6 kids max.",
        element: "air", location: "Aerial Rig",
        limited: true,
        link: "/aerial",
        hosts: ["beth"],
      },
      {
        time: "3:00 PM",
        event: "Paddleboard Yoga",
        detail: "A final all-levels flow on the water — integrate the weekend floating under the open sky.",
        element: "water", location: "Lakeside",
        limited: true,
        link: "/paddleboard",
        hosts: ["alice"],
      },
      {
        time: "3:00 PM",
        event: "Pendulum Readings & Salt Intention Workshop",
        detail: "An immersive workshop on pendulum divination and the art of creating salt intentions — a sacred pre-ceremony practice before the Tarot + Tea.",
        element: "earth", location: "Labyrinth Garden",
        hosts: ["mystical-moon-dance"],
      },
      {
        time: "3:15 PM",
        event: "J Brave",
        detail: "45 minutes of conscious lyricism and heart-forward music.",
        element: "air",
        location: "Main Stage · Live Music",
        hosts: ["j-brave"],
      },
      {
        time: "4:00 PM",
        event: "ÂKÅTÂLĖ",
        detail: "A live sonic journey to gather the community toward closing.",
        element: "air",
        location: "Main Stage · Live Music",
        hosts: ["akatale"],
      },
      {
        time: "4:00 PM",
        event: "Tarot + Tea Party",
        detail: "The final daily lounge gathering — close the weekend with mystery and magic.",
        element: "air", location: "Lodge · Upstairs Lounge",
        hosts: ["mystical-moon-dance"],
      },
      {
        time: "5:00 PM",
        event: "Closing & Integration Circle",
        detail: "Led by Avalon Starling — a closing circle to integrate the weekend's medicine, share gratitude, and send you home with a full heart.",
        element: "fire", location: "Main Stage",
        hosts: ["avalon-starling"],
      },
      {
        time: "6:00 PM",
        event: "Community Drumming",
        detail: "An open community drumming circle at the fire — everyone is invited to play, move, and sound together as the weekend comes to a close.",
        element: "fire", secondElement: "earth",
        location: "Bonfire",
      },
      {
        time: "7:00 PM",
        event: "Ecstatic Dance",
        detail: "7–9 PM · Close the weekend dancing.",
        element: "fire", secondElement: "air",
        location: "Main Stage",
        fee: "Silk hammock rental available · $20/30 min · See /aerial",
        hosts: ["flowscape"],
      },
    ],
  },
];
